# Generated by Django 4.2.13 on 2024-06-30 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinateEntity',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=31)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('labels', models.ManyToManyField(blank=True, to='entity.label')),
            ],
            options={
                'db_table': 'coordinate_entity',
            },
        ),
    ]
