# Generated by Django 4.2.13 on 2024-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_alter_label_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
